<html>
<head>
   <title><?php echo htmlentities($vt_page_title); ?></title>
   <link rel="stylesheet" type="text/css" href="<?php echo $base; ?>/admin/css/global.css" />
   <script type="text/javascript" src="<?php echo $base; ?>/javascripts/jquery-1.3.2.min.js"></script>
   <script type="text/javascript" src="<?php echo $base; ?>/javascripts/jquery.color.js"></script>
</head>
<body class="yui-skin-sam">
<div id="pageframe">